apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-mqtt-connector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-mqtt-connector
  template:
    metadata:
      labels:
        app: http-mqtt-connector
    spec:
      containers:
        - name: http-mqtt-connector
          image: "{{ .Values.containerImage }}"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/settings
              name: config
      volumes:
        - name: config
          secret:
            secretName: http-mqtt-connector-secret
            items:
              - key: appsettings.json
                path: appsettings.json
