apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-mqtt-connector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-mqtt-connector
  template:
    metadata:
      labels:
        app: http-mqtt-connector
    spec:
      # Use the "mqtt-client" service account which comes with default deployment
      # Otherwise create it with `kubectl create serviceaccount mqtt-client -n azure-iot-operations`
      serviceAccountName: mqtt-client
      containers:
        - name: http-mqtt-connector
          image: "{{ .Values.containerImage }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /app/settings              
            - name: mq-sat
              mountPath: /var/run/secrets/tokens
            - name: trust-bundle
              mountPath: /var/run/certs
      volumes:
        - name: config
          secret:
            secretName: http-mqtt-connector-secret
            items:
              - key: appsettings.json
                path: appsettings.json
        - name: mq-sat
          projected:
            sources:
            - serviceAccountToken:
                path: mq-sat
                audience: aio-mq # Must match audience in BrokerAuthentication
                expirationSeconds: 86400
        - name: trust-bundle
          configMap:
            name: aio-ca-trust-bundle-test-only # Default root CA cert for AIO